<a href="https://colab.research.google.com/github/Addakularanjith123/Practice-sql/blob/main/kaggle_data/Lotus%20Retail%20Dataset%20-%20Power%20BI%20(Multi%20tables)/withoutETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd
import numpy as np

In [2]:
dim_employees=pd.read_csv('/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_employees.csv')

In [3]:
dim_employees

,employee_id,first_name,last_name,gender,role,store_id,hire_date,monthly_salary_egp
0,EMP0001,Ghada,Sayed,Female,Store Manager,1,2018-07-04,14235
1,EMP0002,Nadia,Ali,Female,Sales Associate,1,2023-08-18,4255
2,EMP0003,Samah,Mahmoud,Female,Sales Associate,1,2022-05-27,5287
3,EMP0004,Neveen,Ismail,Female,Store Manager,1,2023-02-02,14854
4,EMP0005,Samir,Mahmoud,Male,Department Manager,1,2024-04-28,8706
...,...,...,...,...,...,...,...,...
211,EMP0212,Karim,Abdallah,Male,Cashier,15,2021-01-21,4484
212,EMP0213,Heba,Barakat,Female,Cashier,15,2019-05-03,5062
213,EMP0214,Magdy,Wahba,Male,Senior Sales Associate,15,2020-07-03,7938
214,EMP0215,Engy,Gamal,Female,Sales Associate,15,2019-07-02,4811
215,EMP0216,Wael,Lotfy,Male,Cashier,15,2019-06-08,3557

In [4]:
dim_employees.isna().sum()

employee_id           0
first_name            0
last_name             0
gender                0
role                  0
store_id              0
hire_date             0
monthly_salary_egp    0
dtype: int64

In [5]:
dim_products=pd.read_csv('/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_products.csv')

In [6]:
dim_products

,product_id,product_name_raw,category,subcategory,brand,unit_price_text,unit_price,unit_cost,stock_qty,is_active
0,CLT0001,T-Shirt | Black | S,Clothing,Tops,Nile Fashion,EGP 90,90,40,449,1
1,CLT0002,T-Shirt | Black | M,Clothing,Tops,Nile Fashion,EGP 90,90,40,94,1
2,CLT0003,T-Shirt | Black | L,Clothing,Tops,Nile Fashion,EGP 90,90,40,444,1
3,CLT0004,T-Shirt | Black | XL,Clothing,Tops,Nile Fashion,EGP 90,90,40,408,1
4,CLT0005,T-Shirt | White | S,Clothing,Tops,Nile Fashion,EGP 90,90,40,22,1
...,...,...,...,...,...,...,...,...,...,...
340,ELC0341,Epson EcoTank L3250,Electronics,Printers,Epson,EGP 5900,5900,4700,46,1
341,ELC0342,Canon PIXMA G3420,Electronics,Printers,Canon,EGP 5100,5100,4000,66,1
342,ELC0343,Sony PS5 Console,Electronics,Gaming,Sony,EGP 18500,18500,14800,45,1
343,ELC0344,Nintendo Switch OLED,Electronics,Gaming,Nintendo,EGP 13200,13200,10500,67,0
344,ELC0345,Xbox Series S,Electronics,Gaming,Microsoft,EGP 10200,10200,8100,46,1

In [7]:
dim_products.isna().sum()

product_id          0
product_name_raw    0
category            0
subcategory         0
brand               0
unit_price_text     0
unit_price          0
unit_cost           0
stock_qty           0
is_active           0
dtype: int64

In [8]:
dim_store=pd.read_csv('/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_stores.csv')

In [9]:
dim_store

,store_id,store_name,city,district,region,opening_year,size_sqm,store_type
0,1,Lotus Cairo Festival City,Cairo,New Cairo,Greater Cairo,2018,420,Flagship
1,2,Lotus Mall of Egypt,Giza,Sheikh Zayed,Greater Cairo,2019,380,Flagship
2,3,Lotus City Stars,Cairo,Nasr City,Greater Cairo,2017,350,Flagship
3,4,Lotus Alexandria City Centre,Alexandria,Smouha,Alexandria,2020,290,Standard
4,5,Lotus San Stefano,Alexandria,San Stefano,Alexandria,2016,310,Standard
5,6,Lotus Mansoura Mega Mall,Mansoura,El Mansoura,Nile Delta,2021,220,Standard
6,7,Lotus Tanta Stars,Tanta,El Tanta,Nile Delta,2022,180,Small
7,8,Lotus Aswan Plaza,Aswan,El Aswan,Upper Egypt,2019,150,Small
8,9,Lotus Luxor Mall,Luxor,El Luxor,Upper Egypt,2020,140,Small
9,10,Lotus Hurghada Waterfront,Hurghada,El Mamsha,Red Sea,2018,200,Standard
10,11,Lotus Suez Canal Mall,Suez,El Arbain,Canal Zone,2021,170,Small
11,12,Lotus Port Said Mega,Port Said,El Manakh,Canal Zone,2017,190,Small
12,13,Lotus Ismailia Festival,Ismailia,El Hay El Awel,Canal Zone,2022,160,Small
13,14,Lotus Zagazig Stars,Zagazig,El Zagazig,Nile Delta,2020,175,Small
14,15,Lotus Sharm Plaza,Sharm El Sheikh,Nabq Bay,South Sinai,2019,210,Standard

In [10]:
dim_store.isna().sum()

store_id        0
store_name      0
city            0
district        0
region          0
opening_year    0
size_sqm        0
store_type      0
dtype: int64